charmverse/core

package.json, src/prisma/migrations/20231118102543_ban_user/migration.sql, src/prisma/schema.prisma
=> Blacklist user prisma schema model

package.json, src/lib/permissions/spaces/client/interfaces.ts, src/lib/permissions/spaces/client/spacePermissionsHttpClient.ts
=> Removed old bounties code

package.json, src/prisma/migrations/20231201011557_add_sort_to_criteria/migration.sql, src/prisma/schema.prisma
guess i completely missed this!
=> add sort column to rubric criteria

package.json, src/prisma/migrations/20231128103707_required_member_property/migration.sql, src/prisma/migrations/20231129122110_user_details_name/migration.sql, src/prisma/schema.prisma
=> Prisma schema updates for required member properties

package.json, src/prisma/migrations/20231207105743_remove_bounty_inprogress/migration.sql, src/prisma/schema.prisma
=> Remove inProgress reward status

package.json, src/lib/pages/interfaces.ts, src/lib/permissions/getSpacePermissionsType.ts, src/lib/permissions/pages/client/interfaces.ts, src/lib/permissions/pages/client/pagePermissionsHttpClient.ts, src/lib/permissions/pages/interfaces.ts, src/lib/permissions/proposals/client/interfaces.ts, src/lib/permissions/proposals/client/proposalPermissionsHttpClient.ts, src/lib/permissions/proposals/interfaces.ts, src/lib/proposals/interfaces.ts, src/lib/utilities/array.ts, src/lib/utilities/strings.ts, src/permissions.ts
Update interfaces to support permissions model switching
Maintain retrocompatibility, but allow for new permissions model
=> Update core interfaces

package.json, src/lib/permissions/getSpaceInfoViaResource.ts, src/lib/permissions/pages/client/interfaces.ts, src/lib/permissions/pages/client/pagePermissionsHttpClient.ts, src/lib/permissions/permissionsApiClient.class.ts, src/lib/permissions/proposals/client/interfaces.ts, src/lib/permissions/proposals/policies/__tests__/policyArchivedViewOnly.spec.ts, src/lib/permissions/proposals/policies/__tests__/policyStatusDiscussionEditableCommentable.spec.ts, src/lib/permissions/proposals/policies/__tests__/policyStatusDraftNotViewable.spec.ts, src/lib/permissions/proposals/policies/__tests__/policyStatusEvaluationActiveCommentable.spec.ts, src/lib/permissions/proposals/policies/__tests__/policyStatusEvaluationClosedViewOnly.spec.ts, src/lib/permissions/proposals/policies/__tests__/policyStatusReviewCommentable.spec.ts, src/lib/permissions/proposals/policies/__tests__/policyStatusReviewedOnlyCreateVote.spec.ts, src/lib/permissions/proposals/policies/__tests__/policyStatusVoteActiveOnlyVotable.spec.ts, src/lib/permissions/proposals/policies/__tests__/policyStatusVoteClosedViewOnly.spec.ts, src/lib/permissions/proposals/policies/index.ts, src/lib/permissions/proposals/policies/interfaces.ts, src/lib/permissions/spaces/client/interfaces.ts, src/lib/permissions/spaces/client/spacePermissionsHttpClient.ts, src/lib/testing/__tests__/user.spec.ts, src/lib/testing/user.ts, src/permissions.ts
Deprecate page permissions client
Increase usage of permissions api client
=> Deprecate base page permissions client

package.json, src/lib/proposals/__tests__/getCurrentEvaluation.spec.ts, src/lib/proposals/utils.ts
=> getCurrentEvaluation can return undefined

package.json, src/prisma/migrations/20231227130016_create_proposal_operation/migration.sql, src/prisma/schema.prisma
=> Add create proposals operation to Space permissions

package.json, src/lib/testing/proposals.ts
=> dont require category input in test generator

package.json, src/lib/proposals/interfaces.ts, src/lib/testing/proposals.ts
=> return evaluations when geenerating proposals for test

package.json, src/lib/pages/resolvePageTree.ts
Fix for exporting database and pages
=> Include spaceId when fetching page from resolvePageTree

package.json, src/prisma/migrations/20240107143727_proposal_notification_evaluationid/migration.sql, src/prisma/schema.prisma
=> Added evaluationId to proposal notification

.husky/pre-commit, package.json
=> bump prisma client

.vscode/settings.json, package.json, src/prisma/schema.prisma
=> attempt to fix openssl for node v18 update

package.json, src/prisma/migrations/20240120011032_default_fields/migration.sql, src/prisma/schema.prisma
=> add default empty object for proposal.fields

package.json, src/prisma/migrations/20240119092134_field_answer_comment/migration.sql, src/prisma/schema.prisma
=> Added field answer id to thread model

package.json, src/prisma/migrations/20240125102027_custom_credential_logo/migration.sql, src/prisma/schema.prisma
=> Added credentials logo to space model

package.json, src/prisma/migrations/20240125134232_primary_wallet/migration.sql, src/prisma/migrations/20240126095634_user_primary_wallet/migration.sql, src/prisma/schema.prisma
=> Add primary boolean field to user wallet model

package.json, src/lib/testing/__tests__/user.spec.ts, src/lib/testing/user.ts, src/prisma/migrations/20240130115026_public_proposal_templates/migration.sql, src/prisma/schema.prisma
Add space setting for public templates
=> Public proposal templates

package.json, src/lib/testing/pages.ts, src/lib/testing/proposals.ts, src/prisma/migrations/20240130174034_add_proposal_notes_type/migration.sql, src/prisma/schema.prisma
I considered the singular form, "proposal_note", but it just sounds funny. Technically a single page can include multiple notes 🤷
=> extend PageType with proposal_notes

package.json, src/prisma/migrations/20240130222126_add_home_page/migration.sql, src/prisma/schema.prisma
=> add home page column to space table

package.json, src/lib/testing/pages.ts, src/lib/testing/proposals.ts, src/prisma/migrations/20240205173434_remove_page_snapshot/migration.sql, src/prisma/schema.prisma
This reverts commit fc3949084f35259891e327d97b02cb6ff02b5d06.
=> remove snapshotProposalId from pages

package.json, src/prisma/migrations/20240207210436_block_count_index/migration.sql, src/prisma/schema.prisma
Fix slow query related to lack of index
=> Add blockCount index on createdAt

package.json, src/lib/testing/__tests__/proposals.spec.ts, src/lib/testing/proposals.ts
=> Ensure evaluation inputs pass the vote settings

package.json, src/prisma/migrations/20240216165100_index_evaluation_id/migration.sql, src/prisma/schema.prisma
=> add index to evaluationId in proposal reviewers

package.json, src/lib/testing/forums.ts, src/lib/testing/pages.ts
=> remove default content from post and page test generators

.vscode/settings.json, package.json, src/prisma/migrations/20240304190117_add_testnet_option/migration.sql, src/prisma/migrations/20240304192221_add_testnetes/migration.sql, src/prisma/schema.prisma
=> add setting to enable testnets on a space

.github/workflows/test.yml, package.json
=> change how core gets deployed downstream

.github/workflows/test.yml, package.json
=> dont need downstream tests to deploy

.github/workflows/test.yml, package.json
=> actually push the changes

package.json, src/lib/permissions/proposals/client/interfaces.ts, src/lib/permissions/proposals/client/proposalPermissionsHttpClient.ts, src/lib/permissions/proposals/interfaces.ts
=> Bulk compute proposal permissions interface

package.json, src/prisma/migrations/20240307132348_issue_credentials_onchain/migration.sql, src/prisma/schema.prisma
Allow spaces to issue credentials onchain
=> Add chain for issuing credentials

package.json
=> bump typescript

.vscode/settings.json, package.json
What I think we want: Have Prettier extension fix code and auto-fix imports on save
=> simplify vs code settings

package.json, src/prisma/migrations/20240312082621_total_charms_balance/migration.sql, src/prisma/schema.prisma
Total historical chamrs balance for leaderboard
=> total charms balance

package.json, src/prisma/schema.prisma
=> user index

package.json, src/prisma/migrations/20240313204811_extend_credential_fields/migration.sql
Remove extra index addition that caused an error
=> Fix migration file

package.json, src/prisma/migrations/20240320192251_add_board_id_index/migration.sql, src/prisma/schema.prisma
=> index page.boardId

package.json, src/prisma/migrations/20240328050614_optional_project_fields/migration.sql, src/prisma/schema.prisma
=> Made project and member fields optional

package.json, src/prisma/migrations/20240411194407_add_proposal_indices/migration.sql, src/prisma/migrations/20240411194526_add_form_space_id/migration.sql, src/prisma/migrations/20240411194709_add_form_space_id/migration.sql, src/prisma/schema.prisma
=> add missing indices for proposal-related tables

package.json, src/prisma/migrations/20240418103611_projects_deleted_at/migration.sql, src/prisma/schema.prisma
We want to mark projects as deleted
=> Add deletedAt for Projects

package.json, src/prisma/migrations/20240423094857_reward_draft_status/migration.sql, src/prisma/schema.prisma
=> Reward draft status

package.json, src/lib/pages/interfaces.ts, src/prisma/migrations/20240422132537_page_lens_post_link/migration.sql, src/prisma/schema.prisma
=> Add lens post link for page model

package.json, src/prisma/migrations/20240424041530_removed_proposal_lens/migration.sql, src/prisma/schema.prisma
=> Removed lensPostLink column from proposal model

package.json, src/prisma/migrations/20240426001007_application_messagenodes/migration.sql, src/prisma/migrations/20240426055528_application_messagenodes/migration.sql, src/prisma/schema.prisma
=> Added application message nodes

package.json, src/prisma/migrations/20240425213730_add_reward_type/migration.sql, src/prisma/schema.prisma
i want to require rewardType, but setting to "none" for now, then we'll run a migration and then i will remove the default value.
=> add reward type to bounties

package.json, src/lib/proposals/interfaces.ts, src/prisma/migrations/20240430120827_proposal_evaluation_button_labels/migration.sql, src/prisma/migrations/20240502212938_proposal_evaluation_action_label/migration.sql, src/prisma/schema.prisma
=> Proposal evaluation action button labels

package.json, src/lib/proposals/__tests__/getCurrentEvaluation.spec.ts, src/lib/proposals/interfaces.ts, src/lib/proposals/utils.ts, src/prisma/migrations/20240514120228_proposal_evaluation_final_step/migration.sql, src/prisma/schema.prisma
=> Added final step to workflow step json

package.json, src/prisma/migrations/20240522121311_drop_evaluation_review_appeal/migration.sql, src/prisma/schema.prisma
=> Drop appeal column from proposal evaluation review table

package.json, src/prisma/migrations/20240528133512_evaluation_appeal_reason/migration.sql, src/prisma/schema.prisma
=> Added appeal reason in proposal evaluation

package.json, src/lib/proposals/interfaces.ts, src/prisma/migrations/20240605083134_workflow_notification_labels/migration.sql, src/prisma/migrations/20240605101451_workflow_notifications/migration.sql, src/prisma/schema.prisma
=> Added notification labels for proposal evaluation step

package.json, src/prisma/migrations/20240604032100_github_prs/migration.sql, src/prisma/schema.prisma
=> PR Summaries

package.json, src/prisma/migrations/20240612124102_rubric_criteria_answer_user/migration.sql, src/prisma/schema.prisma
=> User relation for ProposalRubricCriteriaAnswer model

package.json, src/prisma/migrations/20240612124102_rubric_criteria_answer_user/migration.sql
Contains the change that ensures the db schema update will work
=> Fix the migration

package.json, src/prisma/migrations/20240618112758_farcaster_member_property/migration.sql, src/prisma/schema.prisma
=> Farcaster member property type

package.json, src/prisma/migrations/20240621104710_connectapp_onboarding/migration.sql, src/prisma/migrations/20240626092150_connectapp_onboarding/migration.sql, src/prisma/schema.prisma
Flag for onboarding the user in connect app.
=> Connect app - Onboarding user

package.json, src/prisma/migrations/20240527150955_drop_unique_docusign_accountid/migration.sql, src/prisma/schema.prisma
=> Drop unique docusign account requirement

package.json, src/prisma/migrations/20240624093448_op_project_form_field/migration.sql, src/prisma/migrations/20240626161306_optimism_project_profile/migration.sql, src/prisma/schema.prisma
[Card](https://app.charmverse.io/charmverse/allow-users-to-select-projects-from-op-576010101925365)
=> Added op_project form field type

package.json, src/prisma/migrations/20240702121639_project_og_image/migration.sql, src/prisma/migrations/20240703083842_/migration.sql, src/prisma/schema.prisma
A place to save the farcaster image url
=> Add frame image to Project schema

package.json, src/prisma/migrations/20240703091206_connect_project_path/migration.sql, src/prisma/migrations/20240705091256_connect_project_path/migration.sql, src/prisma/schema.prisma
=> Added project optional path

package.json, src/prisma/migrations/20240725094131_sunny_project_fields/migration.sql, src/prisma/migrations/20240726093404_sunny_project_fields/migration.sql, src/prisma/schema.prisma
=> Add sunny project fields

package.json, src/prisma/migrations/20240726092223_proposal_published_at/migration.sql, src/prisma/schema.prisma
=> Proposal published at column

package.json, src/prisma/migrations/20240801123841_proposal_permissions_upgrade/migration.sql, src/prisma/schema.prisma
=> Add support for workflow-based permissions

package.json, src/prisma/migrations/20240806230010_add_social_urls/migration.sql, src/prisma/schema.prisma
=> add socialUrls field to team members

package.json
also updating here https://github.com/charmverse/app.charmverse.io/pull/4387
=> upgrade version of undici

package.json, src/prisma/migrations/20240806220150_remove_project_fields/migration.sql, src/prisma/schema.prisma
=> remove fields from project schema that we wont use anymore

package.json, src/prisma/migrations/20240813204933_project_source_farcaster/migration.sql, src/prisma/migrations/20240814112025_frame_text_content/migration.sql, src/prisma/schema.prisma
=> Added farcaster to project source enum

package.json, src/prisma/migrations/20240819192601_add_share_reviews/migration.sql, src/prisma/schema.prisma
=> add flag to enable sharing reviews with non-reviewers

package.json, src/prisma/migrations/20240822183322_add_sunny_category_field/migration.sql, src/prisma/schema.prisma
=> add new field for sunny awards

package.json, src/prisma/migrations/20240821121726_proposal_evaluation_due_date/migration.sql, src/prisma/schema.prisma
=> Added due date to proposal evaluation

package.json, src/lib/proposals/interfaces.ts, src/lib/testing/proposals.ts
=> Updated proposal test utils for evaluation due date

package.json, src/prisma/migrations/20240826125047_add_gitcoin_attestation_type/migration.sql, src/prisma/schema.prisma
=> Add gitcoin project attestation type

package.json, src/prisma/migrations/20240827140657_add_waitlist_percentile/migration.sql, src/prisma/schema.prisma
=> Add waitlist percentile

package.json, src/prisma/migrations/20240903092753_waitlist_github_login/migration.sql, src/prisma/schema.prisma
=> Add github login to model

package.json, src/prisma/schema.prisma
=> Revert "add project source for product updates"

package.json, src/prisma/migrations/20240909051816_add_tokengate_message/migration.sql, src/prisma/schema.prisma
=> add field to store token gate message for spaces

package.json, src/prisma/migrations/20240912190121_waitlist_partners/migration.sql, src/prisma/schema.prisma
=> Enable partner accounts

package.json, src/prisma/migrations/20240920042503_update_scout/migration.sql, src/prisma/schema.prisma
=> add createdAt and new onboarding fields for scout game

package.json, src/prisma/migrations/20240923115000_optional_fields_points/migration.sql, src/prisma/schema.prisma
=> Optional fields for sg models

package.json, src/prisma/migrations/20240925211002_weekly_stats_rank/migration.sql, src/prisma/migrations/20240926110643_weekly_stats_rank/migration.sql, src/prisma/schema.prisma
=> Added rank field to User weekly stats model

package.json, src/prisma/migrations/20240926204918_update_season_type/migration.sql, src/prisma/migrations/20240926205111_update_season_type/migration.sql, src/prisma/schema.prisma
=> Use isoweek for season fields also

package.json, src/prisma/migrations/20240927012029_remove_builder_field/migration.sql, src/prisma/schema.prisma
=> Remove builder column, replaced with "builderStatus"

package.json, src/prisma/migrations/20240927094539_builder_event_bonus/migration.sql, src/prisma/schema.prisma
=> Builder event bonus partner

package.json, src/prisma/migrations/20240930155752_update_github_repo/migration.sql, src/prisma/schema.prisma
=> add deletedAt field to git repos

package.json, src/prisma/migrations/20241003022742_uniq_scout_farcaster/migration.sql, src/prisma/schema.prisma
=> make farcaster unique in scouts table

package.json, src/prisma/migrations/20241002161400_ondelete_cascade_scout_game_activity/migration.sql, src/prisma/schema.prisma
=> Delete activity when event is deleted

package.json, src/prisma/migrations/20241003173005_add_fork_to_repos/migration.sql, src/prisma/schema.prisma
=> track if a git repo is a fork

package.json, src/prisma/migrations/20241003160529_congrats_image_url/migration.sql, src/prisma/schema.prisma
When a user shares a builder user page.
=> Congrats image url

package.json, src/prisma/migrations/20241004181131_add_git_commits/migration.sql, src/prisma/schema.prisma
=> add git commit events

package.json, src/prisma/migrations/20241007190634_add_misc_type/migration.sql, src/prisma/schema.prisma
=> add misc event type for attributing points to builders and scouts

package.json, src/prisma/migrations/20241024235208_default_counts/migration.sql, src/prisma/schema.prisma
fixes a bug where the record is created with "null" and then i dont think increment actually does anything
=> add default counts to stats

package.json, src/prisma/migrations/20241025122636_builder_activity/migration.sql, src/prisma/migrations/20241025164941_add_builder_activity/migration.sql, src/prisma/schema.prisma
=> Builder card activity schema

package.json, src/prisma/migrations/20241029224614_remove_scout_username/migration.sql, src/prisma/schema.prisma
=> drop scout.username

package.json, src/prisma/migrations/20241112115924_edit_rewards_operation/migration.sql, src/prisma/schema.prisma
=> Add edit rewards operation

src/prisma/migrations/20241206225428_add_indicies/migration.sql, src/prisma/schema.prisma
=> add indices on builder nft

.github/workflows/test.yml, package.json
=> deploy to scoutgame.xyz

package.json, src/prisma/migrations/20241220183119_add_referal_completedat/migration.sql, src/prisma/schema.prisma
=> add completedAt to referral table

package.json, src/prisma/migrations/20241226125048_points_receipt_season/migration.sql, src/prisma/schema.prisma
=> Added season field to points receipt

package.json, src/prisma/migrations/20241230105553_required_receipt_season/migration.sql, src/prisma/schema.prisma
=> Made season required for points receipt model

package.json, src/prisma/migrations/20241231123634_referral_bonus_event/migration.sql, src/prisma/schema.prisma
=> Added bonus builder event to referral event

package.json, src/prisma/migrations/20241231144857_send_transaction_emails/migration.sql, src/prisma/schema.prisma
=> Send transaction emails field for scout model

package.json, src/prisma/migrations/20250106144549_social_quest_season/migration.sql, src/prisma/migrations/20250106144625_social_quest_season/migration.sql, src/prisma/schema.prisma
=> Added season to social quest

package.json, src/prisma/migrations/20250107130748_required_quest_season/migration.sql, src/prisma/schema.prisma
=> Required season in social quest model

package.json, src/prisma/migrations/20250107134730_user_rankings_payouts/migration.sql, src/prisma/migrations/20250107155205_user_rankings_payouts/migration.sql, src/prisma/schema.prisma
=> Builder level and expected payout

src/prisma/migrations/20250109164630_form_field_answer_unique/migration.sql, src/prisma/schema.prisma
=> Added unique constraint for form field answer

package.json, src/prisma/migrations/20250113153529_builder_card_activity_14d/migration.sql, src/prisma/migrations/20250113185651_builder_card_activity_14d/migration.sql, src/prisma/schema.prisma
=> Added last 14 days for builder card activity

package.json, src/prisma/migrations/20250113231820_default_builder_stats/migration.sql, src/prisma/migrations/20250113232128_default_builder_stats/migration.sql, src/prisma/schema.prisma
=> Added default value for builder stats

package.json, src/prisma/migrations/20250116121322_telegram_name/migration.sql, src/prisma/schema.prisma
=> Added telegram name in scout model

package.json, src/prisma/migrations/20250123183245_scout_project/migration.sql, src/prisma/schema.prisma
=> Scout project model

package.json, src/prisma/migrations/20250127190020_add_unreviewed_pr/migration.sql, src/prisma/schema.prisma
=> add receipt type for unreviewed prs

package.json, src/prisma/migrations/20250128044928_scout_project_path/migration.sql, src/prisma/schema.prisma
=> Added path to scout project model

package.json, src/lib/pages/mapPageTree.ts, src/lib/permissions/pages/client/pagePermissionsHttpClient.ts, src/lib/proposals/utils.ts, src/lib/utilities/__tests__/array.spec.ts, src/lib/utilities/array.ts, src/lib/utilities/objects.ts
=> remove dependency on lodash

package.json, src/lib/permissions/getSpaceInfoViaResource.ts, src/lib/testing/forums.ts, src/lib/testing/proposals.ts, src/lib/testing/spaces.ts, src/lib/testing/user.ts, src/lib/utilities/strings.ts
just trying to bring down the package size
=> remove nanoid dependency

.github/workflows/test.yml, package.json, src/lib/http/errors.ts, src/lib/http/fetch.ts
=> update minor libs

package.json, src/prisma/migrations/20250213231533_scout_utm_campaign/migration.sql, src/prisma/schema.prisma
=> Scout utm campaign field

package.json, src/lib/testing/credentials.ts, src/prisma/schema.prisma
=> remove offchain credential code

package.json, src/prisma/migrations/20250221111729_github_repo_avatar/migration.sql, src/prisma/schema.prisma
=> Added github repo avatar field

package.json, src/prisma/migrations/20250304162753_frames_notification_token/migration.sql, src/prisma/schema.prisma
=> Added scout frames notification token

package.json, src/prisma/migrations/20250305195947_add_daily_stats/migration.sql, src/prisma/schema.prisma
=> add daily stats for wallet analytics

package.json, src/prisma/migrations/20250307050859_add_nonullable/migration.sql, src/prisma/migrations/20250307080108_add_contract_stats/migration.sql, src/prisma/schema.prisma
=> add contract daily stats

package.json, src/prisma/migrations/20250327155525_add_repliaedat/migration.sql, src/prisma/schema.prisma
=> add date a builder reapplies

package.json, src/prisma/migrations/20250404213555_remove_matchup_developer_id/migration.sql, src/prisma/schema.prisma
=> remove developerId on matchup selections

package.json, src/prisma/migrations/20250409132131_partner_reward_payout_provider/migration.sql, src/prisma/migrations/20250409141412_partner_reward_payout_provider/migration.sql, src/prisma/schema.prisma
=> Added partner reward payout contract provider

package.json, src/prisma/migrations/20250520162507_optional_space_contribution_wallet/migration.sql, src/prisma/schema.prisma
=> Optional space contribution wallet

package.json, src/prisma/migrations/20250529140726_space_subscription_tx_unique/migration.sql, src/prisma/schema.prisma
=> Space subscription unique tx

package.json, src/prisma/migrations/20250526133223_archive_resources/migration.sql, src/prisma/migrations/20250527012047_non_optional_archived/migration.sql, src/prisma/schema.prisma
=> Archived workflow, token gates and roles
