charmverse/core

- package.json
- src/lib/testing/__tests__/user.spec.ts
- src/lib/testing/user.ts
- src/prisma/migrations/20230718220322_add_paid_tier_community/migration.sql
- src/prisma/migrations/20230718220451_default_paid_tier/migration.sql
- src/prisma/schema.prisma
I plan on doing this in two steps:
1) add 'community' as a new default and update app.charmverse to support both values
2) migrate all spaces to 'community' and then remove 'pro' from the enum
> add new 'community' tier to enum

- README.md
- package.json
- src/lib/testing/__tests__/proposals.spec.ts
- src/prisma/migrations/20231213040736_additional_identity_type/migration.sql
- src/prisma/migrations/20231214073309_add_vote_settings/migration.sql
- src/prisma/schema.prisma
I need users to be able to save vote settings before we actually create them. Currently any vote stored in the db is considered active, we also don't need all the fields, particularly "deadline" which is required, so I decided to just add a settings json for evaluation which we'll use as a template when the step is initiated.
> add voteSettings to evaluations

- package.json
- src/lib/permissions/proposals/client/interfaces.ts
- src/lib/permissions/proposals/client/proposalPermissionsHttpClient.ts
Extend permissions API Client
We want ability to get permissions for a user throughout evaluation step
> Enable getting all permissions for the proposal

- package.json
- src/lib/log/logLevel.ts
- src/lib/permissions/__tests__/hasAccessToSpace.spec.ts
- src/lib/permissions/core/interfaces.ts
- src/lib/permissions/core/policies.ts
- src/lib/permissions/hasAccessToSpace.ts
- src/prisma/migrations/20240206190023_add_xps_user_field/migration.sql
- src/prisma/schema.prisma
add "xpsUserId" to spaceroles, since users have a new user id in each summon tenant
> add xps user ids to all space roles

- package.json
- src/lib/pages/interfaces.ts
we can optimize page load by not retrieving cards by default. I noticed tehre's also a big delay when retrieving rewrad for charmverse, even though we only have about 20. Most of the time is getting page permissions
> add a filter for pages request

- package.json
- src/lib/pages/interfaces.ts
We currently use not_card inside usePages() and then we get pages again w/o any filter. But what i'd like to do is use "sidebar_view" to only retrieve the pages that belong in usePages(), so we can still call getAccessiblePagIds() with no filter when searching by text, to return proposals, bounties, or whatever.
I"m open to other names than 'sidebar_view'. Another option could also be to just return a whitelist of page types unless the 'search' prop is passed in, but i think this is more expressive and maybe we will want to use 'filter' to narrow down the search
> add sidebar_view as an option for pages request

- package.json
- src/prisma/migrations/20240322183720_remove_submissions_default/migration.sql
- src/prisma/schema.prisma
There's a bug right now where if someone wants 'infinite' submissions, then the DB pre-populates with 1, even though the UI shows 'infinite' as the default. I am not sure if this affects the product, but if we're expecting a single submission someplace, we can just fix it downstream
> remove default for reward max submissions

- package.json
- src/lib/pages/mapPageTree.ts
we no longer can tell if a page had a "card" as a parent or its parent is just hidden, since cards are not returned to the pages context
i think we could fix this by querying each page's parent as well and marking them to be hidden or not, but that will take a bit more time
> dont show nodes missing a parent in the page tree for now

- package.json
- src/prisma/migrations/20240412184457_cascade_delete_members/migration.sql
- src/prisma/schema.prisma
We should always define a Cascade rule for foreign keys. This basically just says how to handle relations when you delete something else. If not, we have to remember to manage that logic in our code or delete ops can fail.
Since userId is optional on team members, I changes it to just set the userId to null.
> delete team members when a project is deleted

- package.json
- src/prisma/migrations/20240816165545_add_category_fields/migration.sql
- src/prisma/schema.prisma
We'll remove 'category' from the db and from CharmVerse attestations in a follow-up PR
> add new category fields for projects so we dont mix it up

- package.json
- src/prisma/migrations/20240819165029_add_admin_archive/migration.sql
- src/prisma/schema.prisma
This is part of a small feature request for Polygon: If a proposal is archived by admin, authors should not be able to un-archive.
At first i was going to add 'archivedBy' and do a look-up on the user, also considered an 'archivedAt' field.. but those two fields could also be found in a log someplace. By just having 'archivedByAdmin', we don't need to add another JOIN to the proposals lookup, and if the user leaves or changes roles, it won't change the fact this proposal cannot be unarchived
> Add flag 'Archived by admin' to proposals

- package.json
- src/prisma/schema.prisma
This addition replaces changing the underlying data model for Product Updates and allows us to keep using the current models. We might want to filter these types of projects out of wiki, etc in the future.
> add project source for product updates

- package.json
- src/prisma/migrations/20241029103127_scout_path/migration.sql
- src/prisma/migrations/20241029112455_scout_path/migration.sql
- src/prisma/schema.prisma
> Scout model path

- package.json
- src/prisma/migrations/20241205174706_update_scout/migration.sql
- src/prisma/migrations/20241205175221_scout_merge_events/migration.sql
- src/prisma/schema.prisma
Allows us to merge scout accounts without actually deleting the scout record
This time, I thought we could create a table to track all the things we merge (farcaster id, wallet, etc). The schema will be defined in Typescript. This won't be used by production code but could save a lot of time if we are trying to debug what happened.
Also added a couple indices that should help
> add deletedAt and mergedTo

- package.json
- src/prisma/migrations/20241206175837_add_partner_bonus/migration.sql
- src/prisma/schema.prisma
First use case is to keep track of moxie we have sent to each user each week so we don't send it twice. We can also use this to show you if you received Moxie in the points claim email
> add partner reward

- package.json
- src/prisma/migrations/20250107212522_add_email_verification/migration.sql
- src/prisma/schema.prisma
when sending yuou a verification, we'll create a record with a unique code. When checking your email is validated we will look at this collection (as opposed to adding another field to scout table or something, which would be faster lookups but redundant, possibly incorrect data)
> add model to store email verifications

- package.json
- src/lib/protocol/easSchemas/constants.ts
The current version has some dependencies with sec vulnerabilities.
Changelog: https://github.com/ethereum-attestation-service/eas-sdk/blob/master/CHANGELOG.md
> bump eas version to 2

- package.json
- src/prisma/migrations/20250415034354_remove_provider_default/migration.sql
- src/prisma/schema.prisma
we need to force code to specify provider because there is no natural "default'. For example, if we didn't have a default we might have caught the bug that broke the matchup airdrop before the user encountered it
> require contract provider to be stated

- package.json
- src/prisma/migrations/20250530163912_update_logs_cache/migration.sql
- src/prisma/migrations/20250530164111_update_logs_cache/migration.sql
- src/prisma/schema.prisma
i realized we're always querying logs with eventName as a filter, so we need to keep track of the 'latest block number' based on the event requested
> add eventName to contract

- package.json
- src/lib/log/logLevel.ts
- src/lib/log/logUtils.ts
- src/lib/log/sendToDatadog.ts
- src/logTest.ts
I tried using Datadog's latest v2 Logs SDK, and it sucks. It doesn't offer many inputs - according to Typescript you only have "message" - and it was impossible for me to get the "level" to work, with and without log pipelines that we have set up. I had much better luck just writing to their API directly, and the library doesn't seem to do anything special like batching, etc.
> send logs to datadog over rest
